drop table site_app_user;
drop table site_app_house;
drop table site_app_flat;
drop table rooms;
drop table django_session;
drop table django_admin_log;
drop table django_migrations;
drop table auth_user_user_permissions;
drop table auth_user_groups;
drop table auth_user;
drop table auth_group_permissions;
drop table auth_group;
drop table auth_permission;
drop table django_content_type;
\dt;
\q;