# Generated by Django 2.2.1 on 2019-05-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=300)),
                ('elevator', models.BooleanField()),
                ('cost_of_place', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('total_size', models.IntegerField()),
                ('living_size', models.IntegerField()),
                ('rooms_count', models.IntegerField()),
                ('floor', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=300)),
                ('elevator', models.BooleanField()),
                ('cost_of_place', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('house_size', models.IntegerField()),
                ('garage', models.BooleanField()),
                ('outdoors_size', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=300)),
                ('elevator', models.BooleanField()),
                ('cost_of_place', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('size', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('count_of_roommate', models.IntegerField()),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nick', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
