# Generated by Django 2.2.1 on 2019-05-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='dd',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='dd',
            field=models.CharField(max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='dd',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
