# Generated by Django 2.2.1 on 2019-05-27 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
