# Generated by Django 2.2.1 on 2019-05-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_auto_20190515_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='dd',
        ),
        migrations.RemoveField(
            model_name='house',
            name='dd',
        ),
        migrations.RemoveField(
            model_name='room',
            name='dd',
        ),
    ]
